// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, org_id, app_id, name, key_hash, key_prefix, is_revoked, created_at, revoked_at
FROM api_keys
WHERE key_hash = $1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, org_id, app_id, name, key_hash, key_prefix, is_revoked, created_at, revoked_at
FROM api_keys
WHERE org_id = $1 AND app_id = $2 AND id = $3
`

type GetAPIKeyByIDParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	AppID pgtype.UUID `json:"app_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) GetAPIKeyByID(ctx context.Context, arg GetAPIKeyByIDParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, arg.OrgID, arg.AppID, arg.ID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertAPIKey = `-- name: InsertAPIKey :one
INSERT INTO api_keys (id, org_id, app_id, name, key_hash, key_prefix, is_revoked, created_at)
VALUES ($1, $2, $3, $4, $5, $6, false, $7)
RETURNING id, org_id, app_id, name, key_hash, key_prefix, is_revoked, created_at, revoked_at
`

type InsertAPIKeyParams struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	AppID     pgtype.UUID        `json:"app_id"`
	Name      string             `json:"name"`
	KeyHash   string             `json:"key_hash"`
	KeyPrefix string             `json:"key_prefix"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, insertAPIKey,
		arg.ID,
		arg.OrgID,
		arg.AppID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.CreatedAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeysByApp = `-- name: ListAPIKeysByApp :many
SELECT id, org_id, app_id, name, key_hash, key_prefix, is_revoked, created_at, revoked_at
FROM api_keys
WHERE org_id = $1 AND app_id = $2 AND (NOT $3 OR is_revoked = false)
ORDER BY created_at DESC
`

type ListAPIKeysByAppParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	AppID      pgtype.UUID `json:"app_id"`
	ActiveOnly interface{} `json:"active_only"`
}

func (q *Queries) ListAPIKeysByApp(ctx context.Context, arg ListAPIKeysByAppParams) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByApp, arg.OrgID, arg.AppID, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AppID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.IsRevoked,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET is_revoked = true,
    revoked_at = $1
WHERE org_id = $2 AND app_id = $3 AND id = $4
RETURNING id, org_id, app_id, name, key_hash, key_prefix, is_revoked, created_at, revoked_at
`

type RevokeAPIKeyParams struct {
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	OrgID     pgtype.UUID        `json:"org_id"`
	AppID     pgtype.UUID        `json:"app_id"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey,
		arg.RevokedAt,
		arg.OrgID,
		arg.AppID,
		arg.ID,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}
