// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaigns.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCampaignsByOrg = `-- name: CountCampaignsByOrg :one
SELECT COUNT(*) FROM campaigns
WHERE org_id = $1
  AND ($2::TEXT IS NULL OR status = $2)
`

type CountCampaignsByOrgParams struct {
	OrgID        pgtype.UUID `json:"org_id"`
	StatusFilter pgtype.Text `json:"status_filter"`
}

func (q *Queries) CountCampaignsByOrg(ctx context.Context, arg CountCampaignsByOrgParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCampaignsByOrg, arg.OrgID, arg.StatusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT id, org_id, name, status, targeting, budget_cents, currency,
       start_date, end_date, created_at, updated_at
FROM campaigns
WHERE org_id = $1 AND id = $2
`

type GetCampaignByIDParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) GetCampaignByID(ctx context.Context, arg GetCampaignByIDParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByID, arg.OrgID, arg.ID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.Targeting,
		&i.BudgetCents,
		&i.Currency,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCampaign = `-- name: InsertCampaign :one
INSERT INTO campaigns (id, org_id, name, status, targeting, budget_cents, currency,
                       start_date, end_date, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11)
RETURNING id, org_id, name, status, targeting, budget_cents, currency, start_date, end_date, created_at, updated_at
`

type InsertCampaignParams struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	Status      string             `json:"status"`
	Targeting   []byte             `json:"targeting"`
	BudgetCents pgtype.Int8        `json:"budget_cents"`
	Currency    string             `json:"currency"`
	StartDate   pgtype.Date        `json:"start_date"`
	EndDate     pgtype.Date        `json:"end_date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertCampaign(ctx context.Context, arg InsertCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, insertCampaign,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Status,
		arg.Targeting,
		arg.BudgetCents,
		arg.Currency,
		arg.StartDate,
		arg.EndDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.Targeting,
		&i.BudgetCents,
		&i.Currency,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCampaignsByOrg = `-- name: ListCampaignsByOrg :many
SELECT id, org_id, name, status, targeting, budget_cents, currency,
       start_date, end_date, created_at, updated_at
FROM campaigns
WHERE org_id = $1
  AND ($2::TEXT IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListCampaignsByOrgParams struct {
	OrgID        pgtype.UUID `json:"org_id"`
	StatusFilter pgtype.Text `json:"status_filter"`
	OffsetVal    int32       `json:"offset_val"`
	LimitVal     int32       `json:"limit_val"`
}

func (q *Queries) ListCampaignsByOrg(ctx context.Context, arg ListCampaignsByOrgParams) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaignsByOrg,
		arg.OrgID,
		arg.StatusFilter,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campaign{}
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Status,
			&i.Targeting,
			&i.BudgetCents,
			&i.Currency,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaigns
SET name = $1, targeting = $2, budget_cents = $3,
    currency = $4, start_date = $5, end_date = $6,
    updated_at = $7
WHERE org_id = $8 AND id = $9
RETURNING id, org_id, name, status, targeting, budget_cents, currency, start_date, end_date, created_at, updated_at
`

type UpdateCampaignParams struct {
	Name        string             `json:"name"`
	Targeting   []byte             `json:"targeting"`
	BudgetCents pgtype.Int8        `json:"budget_cents"`
	Currency    string             `json:"currency"`
	StartDate   pgtype.Date        `json:"start_date"`
	EndDate     pgtype.Date        `json:"end_date"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	OrgID       pgtype.UUID        `json:"org_id"`
	ID          pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaign,
		arg.Name,
		arg.Targeting,
		arg.BudgetCents,
		arg.Currency,
		arg.StartDate,
		arg.EndDate,
		arg.UpdatedAt,
		arg.OrgID,
		arg.ID,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.Targeting,
		&i.BudgetCents,
		&i.Currency,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCampaignStatus = `-- name: UpdateCampaignStatus :one
UPDATE campaigns
SET status = $1, updated_at = $2
WHERE org_id = $3 AND id = $4
RETURNING id, org_id, name, status, targeting, budget_cents, currency, start_date, end_date, created_at, updated_at
`

type UpdateCampaignStatusParams struct {
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	OrgID     pgtype.UUID        `json:"org_id"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaignStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.OrgID,
		arg.ID,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.Targeting,
		&i.BudgetCents,
		&i.Currency,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
