// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: creatives.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCreativesByCampaign = `-- name: CountCreativesByCampaign :one
SELECT COUNT(*) FROM creatives
WHERE org_id = $1 AND campaign_id = $2
`

type CountCreativesByCampaignParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	CampaignID pgtype.UUID `json:"campaign_id"`
}

func (q *Queries) CountCreativesByCampaign(ctx context.Context, arg CountCreativesByCampaignParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCreativesByCampaign, arg.OrgID, arg.CampaignID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCreativeByID = `-- name: GetCreativeByID :one
SELECT id, org_id, campaign_id, name, type, file_url, file_size_bytes,
       preview_url, is_active, created_at, updated_at
FROM creatives
WHERE org_id = $1 AND campaign_id = $2 AND id = $3
`

type GetCreativeByIDParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	CampaignID pgtype.UUID `json:"campaign_id"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) GetCreativeByID(ctx context.Context, arg GetCreativeByIDParams) (Creative, error) {
	row := q.db.QueryRow(ctx, getCreativeByID, arg.OrgID, arg.CampaignID, arg.ID)
	var i Creative
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CampaignID,
		&i.Name,
		&i.Type,
		&i.FileUrl,
		&i.FileSizeBytes,
		&i.PreviewUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCreative = `-- name: InsertCreative :one
INSERT INTO creatives (id, org_id, campaign_id, name, type, file_url,
                       file_size_bytes, preview_url, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11)
RETURNING id, org_id, campaign_id, name, type, file_url, file_size_bytes, preview_url, is_active, created_at, updated_at
`

type InsertCreativeParams struct {
	ID            pgtype.UUID        `json:"id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	CampaignID    pgtype.UUID        `json:"campaign_id"`
	Name          string             `json:"name"`
	Type          string             `json:"type"`
	FileUrl       string             `json:"file_url"`
	FileSizeBytes pgtype.Int8        `json:"file_size_bytes"`
	PreviewUrl    pgtype.Text        `json:"preview_url"`
	IsActive      bool               `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertCreative(ctx context.Context, arg InsertCreativeParams) (Creative, error) {
	row := q.db.QueryRow(ctx, insertCreative,
		arg.ID,
		arg.OrgID,
		arg.CampaignID,
		arg.Name,
		arg.Type,
		arg.FileUrl,
		arg.FileSizeBytes,
		arg.PreviewUrl,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Creative
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CampaignID,
		&i.Name,
		&i.Type,
		&i.FileUrl,
		&i.FileSizeBytes,
		&i.PreviewUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCreativesByCampaign = `-- name: ListCreativesByCampaign :many
SELECT id, org_id, campaign_id, name, type, file_url, file_size_bytes,
       preview_url, is_active, created_at, updated_at
FROM creatives
WHERE org_id = $1 AND campaign_id = $2
ORDER BY created_at ASC
LIMIT 50
`

type ListCreativesByCampaignParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	CampaignID pgtype.UUID `json:"campaign_id"`
}

func (q *Queries) ListCreativesByCampaign(ctx context.Context, arg ListCreativesByCampaignParams) ([]Creative, error) {
	rows, err := q.db.Query(ctx, listCreativesByCampaign, arg.OrgID, arg.CampaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Creative{}
	for rows.Next() {
		var i Creative
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.CampaignID,
			&i.Name,
			&i.Type,
			&i.FileUrl,
			&i.FileSizeBytes,
			&i.PreviewUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
