// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	AppID     pgtype.UUID        `json:"app_id"`
	Name      string             `json:"name"`
	KeyHash   string             `json:"key_hash"`
	KeyPrefix string             `json:"key_prefix"`
	IsRevoked bool               `json:"is_revoked"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type OrgInvite struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	Email      string             `json:"email"`
	Role       string             `json:"role"`
	Token      string             `json:"token"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type OrgMembership struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Organization struct {
	ID        pgtype.UUID        `json:"id"`
	Type      string             `json:"type"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PublisherApp struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	Platform  string             `json:"platform"`
	BundleID  string             `json:"bundle_id"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PublisherRule struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	AppID     pgtype.UUID        `json:"app_id"`
	Type      string             `json:"type"`
	Config    []byte             `json:"config"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
