// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: org_memberships.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMembershipByUserAndOrg = `-- name: GetMembershipByUserAndOrg :one
SELECT id, org_id, user_id, role, created_at
FROM org_memberships
WHERE user_id = $1 AND org_id = $2
`

type GetMembershipByUserAndOrgParams struct {
	UserID pgtype.UUID `json:"user_id"`
	OrgID  pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetMembershipByUserAndOrg(ctx context.Context, arg GetMembershipByUserAndOrgParams) (OrgMembership, error) {
	row := q.db.QueryRow(ctx, getMembershipByUserAndOrg, arg.UserID, arg.OrgID)
	var i OrgMembership
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const insertMembership = `-- name: InsertMembership :one
INSERT INTO org_memberships (id, org_id, user_id, role, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, user_id, role, created_at
`

type InsertMembershipParams struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertMembership(ctx context.Context, arg InsertMembershipParams) (OrgMembership, error) {
	row := q.db.QueryRow(ctx, insertMembership,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
	)
	var i OrgMembership
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listMembershipsByUser = `-- name: ListMembershipsByUser :many
SELECT id, org_id, user_id, role, created_at
FROM org_memberships
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListMembershipsByUser(ctx context.Context, userID pgtype.UUID) ([]OrgMembership, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrgMembership{}
	for rows.Next() {
		var i OrgMembership
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
