// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: org_invites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrgInviteByToken = `-- name: GetOrgInviteByToken :one
SELECT id, org_id, email, role, token, expires_at, accepted_at, created_at
FROM org_invites
WHERE token = $1
`

func (q *Queries) GetOrgInviteByToken(ctx context.Context, token string) (OrgInvite, error) {
	row := q.db.QueryRow(ctx, getOrgInviteByToken, token)
	var i OrgInvite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertOrgInvite = `-- name: InsertOrgInvite :one
INSERT INTO org_invites (id, org_id, email, role, token, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, email, role, token, expires_at, accepted_at, created_at
`

type InsertOrgInviteParams struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertOrgInvite(ctx context.Context, arg InsertOrgInviteParams) (OrgInvite, error) {
	row := q.db.QueryRow(ctx, insertOrgInvite,
		arg.ID,
		arg.OrgID,
		arg.Email,
		arg.Role,
		arg.Token,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i OrgInvite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}
