// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: publisher_rules.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPublisherRulesByApp = `-- name: CountPublisherRulesByApp :one
SELECT COUNT(*) FROM publisher_rules
WHERE org_id = $1 AND app_id = $2
`

type CountPublisherRulesByAppParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	AppID pgtype.UUID `json:"app_id"`
}

func (q *Queries) CountPublisherRulesByApp(ctx context.Context, arg CountPublisherRulesByAppParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPublisherRulesByApp, arg.OrgID, arg.AppID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePublisherRule = `-- name: DeletePublisherRule :exec
DELETE FROM publisher_rules
WHERE org_id = $1 AND app_id = $2 AND id = $3
`

type DeletePublisherRuleParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	AppID pgtype.UUID `json:"app_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) DeletePublisherRule(ctx context.Context, arg DeletePublisherRuleParams) error {
	_, err := q.db.Exec(ctx, deletePublisherRule, arg.OrgID, arg.AppID, arg.ID)
	return err
}

const getPublisherRuleByID = `-- name: GetPublisherRuleByID :one
SELECT id, org_id, app_id, type, config, is_active, created_at, updated_at
FROM publisher_rules
WHERE org_id = $1 AND app_id = $2 AND id = $3
`

type GetPublisherRuleByIDParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	AppID pgtype.UUID `json:"app_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) GetPublisherRuleByID(ctx context.Context, arg GetPublisherRuleByIDParams) (PublisherRule, error) {
	row := q.db.QueryRow(ctx, getPublisherRuleByID, arg.OrgID, arg.AppID, arg.ID)
	var i PublisherRule
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.Type,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPublisherRule = `-- name: InsertPublisherRule :one
INSERT INTO publisher_rules (id, org_id, app_id, type, config, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, app_id, type, config, is_active, created_at, updated_at
`

type InsertPublisherRuleParams struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	AppID     pgtype.UUID        `json:"app_id"`
	Type      string             `json:"type"`
	Config    []byte             `json:"config"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertPublisherRule(ctx context.Context, arg InsertPublisherRuleParams) (PublisherRule, error) {
	row := q.db.QueryRow(ctx, insertPublisherRule,
		arg.ID,
		arg.OrgID,
		arg.AppID,
		arg.Type,
		arg.Config,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PublisherRule
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.Type,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublisherRulesByApp = `-- name: ListPublisherRulesByApp :many
SELECT id, org_id, app_id, type, config, is_active, created_at, updated_at
FROM publisher_rules
WHERE org_id = $1 AND app_id = $2
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListPublisherRulesByAppParams struct {
	OrgID     pgtype.UUID `json:"org_id"`
	AppID     pgtype.UUID `json:"app_id"`
	OffsetVal int32       `json:"offset_val"`
	LimitVal  int32       `json:"limit_val"`
}

func (q *Queries) ListPublisherRulesByApp(ctx context.Context, arg ListPublisherRulesByAppParams) ([]PublisherRule, error) {
	rows, err := q.db.Query(ctx, listPublisherRulesByApp,
		arg.OrgID,
		arg.AppID,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublisherRule{}
	for rows.Next() {
		var i PublisherRule
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AppID,
			&i.Type,
			&i.Config,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePublisherRule = `-- name: UpdatePublisherRule :one
UPDATE publisher_rules
SET config     = $1,
    is_active  = $2,
    updated_at = $3
WHERE org_id = $4 AND app_id = $5 AND id = $6
RETURNING id, org_id, app_id, type, config, is_active, created_at, updated_at
`

type UpdatePublisherRuleParams struct {
	Config    []byte             `json:"config"`
	IsActive  bool               `json:"is_active"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	OrgID     pgtype.UUID        `json:"org_id"`
	AppID     pgtype.UUID        `json:"app_id"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdatePublisherRule(ctx context.Context, arg UpdatePublisherRuleParams) (PublisherRule, error) {
	row := q.db.QueryRow(ctx, updatePublisherRule,
		arg.Config,
		arg.IsActive,
		arg.UpdatedAt,
		arg.OrgID,
		arg.AppID,
		arg.ID,
	)
	var i PublisherRule
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.Type,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
