// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: publisher_apps.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPublisherAppsByOrg = `-- name: CountPublisherAppsByOrg :one
SELECT COUNT(*) FROM publisher_apps
WHERE org_id = $1
`

func (q *Queries) CountPublisherAppsByOrg(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPublisherAppsByOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPublisherAppByBundleID = `-- name: GetPublisherAppByBundleID :one
SELECT id, org_id, name, platform, bundle_id, is_active, created_at, updated_at
FROM publisher_apps
WHERE org_id = $1 AND bundle_id = $2
`

type GetPublisherAppByBundleIDParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	BundleID string      `json:"bundle_id"`
}

func (q *Queries) GetPublisherAppByBundleID(ctx context.Context, arg GetPublisherAppByBundleIDParams) (PublisherApp, error) {
	row := q.db.QueryRow(ctx, getPublisherAppByBundleID, arg.OrgID, arg.BundleID)
	var i PublisherApp
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Platform,
		&i.BundleID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublisherAppByID = `-- name: GetPublisherAppByID :one
SELECT id, org_id, name, platform, bundle_id, is_active, created_at, updated_at
FROM publisher_apps
WHERE org_id = $1 AND id = $2
`

type GetPublisherAppByIDParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) GetPublisherAppByID(ctx context.Context, arg GetPublisherAppByIDParams) (PublisherApp, error) {
	row := q.db.QueryRow(ctx, getPublisherAppByID, arg.OrgID, arg.ID)
	var i PublisherApp
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Platform,
		&i.BundleID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPublisherApp = `-- name: InsertPublisherApp :one
INSERT INTO publisher_apps (id, org_id, name, platform, bundle_id, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, name, platform, bundle_id, is_active, created_at, updated_at
`

type InsertPublisherAppParams struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	Platform  string             `json:"platform"`
	BundleID  string             `json:"bundle_id"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertPublisherApp(ctx context.Context, arg InsertPublisherAppParams) (PublisherApp, error) {
	row := q.db.QueryRow(ctx, insertPublisherApp,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Platform,
		arg.BundleID,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PublisherApp
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Platform,
		&i.BundleID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublisherAppsByOrg = `-- name: ListPublisherAppsByOrg :many
SELECT id, org_id, name, platform, bundle_id, is_active, created_at, updated_at
FROM publisher_apps
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListPublisherAppsByOrgParams struct {
	OrgID     pgtype.UUID `json:"org_id"`
	OffsetVal int32       `json:"offset_val"`
	LimitVal  int32       `json:"limit_val"`
}

func (q *Queries) ListPublisherAppsByOrg(ctx context.Context, arg ListPublisherAppsByOrgParams) ([]PublisherApp, error) {
	rows, err := q.db.Query(ctx, listPublisherAppsByOrg, arg.OrgID, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublisherApp{}
	for rows.Next() {
		var i PublisherApp
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Platform,
			&i.BundleID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePublisherApp = `-- name: UpdatePublisherApp :one
UPDATE publisher_apps
SET name       = $1,
    is_active  = $2,
    updated_at = $3
WHERE org_id = $4 AND id = $5
RETURNING id, org_id, name, platform, bundle_id, is_active, created_at, updated_at
`

type UpdatePublisherAppParams struct {
	Name      string             `json:"name"`
	IsActive  bool               `json:"is_active"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	OrgID     pgtype.UUID        `json:"org_id"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdatePublisherApp(ctx context.Context, arg UpdatePublisherAppParams) (PublisherApp, error) {
	row := q.db.QueryRow(ctx, updatePublisherApp,
		arg.Name,
		arg.IsActive,
		arg.UpdatedAt,
		arg.OrgID,
		arg.ID,
	)
	var i PublisherApp
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Platform,
		&i.BundleID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
